server:
  port: 80
#Eureka配置
eureka:
  client:
    register-with-eureka: false  #表示是否想注册中心注册自己
    service-url:  #监控页面eureka.instance.hostname
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
