server:
  port: 8001
#mybatis
mybatis:
  type-aliases-package: com.lzq.springcloud.pojo
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml



#spring配置
spring:
  application:
    name: springcould-dept
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: 123456