server:
  port: 7002
#Eureka配置
eureka:
  instance:
    hostname: eureka7002.com    #eureka服务端的实例名称
  client:
    register-with-eureka: false  #表示是否想注册中心注册自己
    fetch-registry: false   #fetch-registry如果为false，则表示自己注册自己
    service-url:  #监控页面eureka.instance.hostname
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
